# On every push this script is executed
on: [push, workflow_dispatch]
name: Build and push obisidan-zola to pasges branch 
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        # In the spot where it says v0.1.3.2-testing, update that to the latest release tag on a new release to continue getting new updates
        uses: trwbox/obsidian-zola-build-action@v0.1.3.2-testing
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Using zola fork for html changes
          ZOLA_REPO: https://github.com/rwtechwiki/obsidian-zola.git
      - name: deploy
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
