name: Build and Deploy Webite
on:
  push:
    branches:
      - publish #master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        uses: trwbox/obsidian-zola-build-action@v0.1.3.2-testing
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZOLA_REPO: https://github.com/rwtechwiki/obsidian-zola.git
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          state-name: ../.ftp-deploy-sync-state.json
          exclude: |
            **/.git*
            **/.git*/**
            netlify.toml
